"""Add ComparisonHistory

Revision ID: 784cd7b78d54
Revises: f2be59aa8a2a
Create Date: 2026-03-26 09:40:32.324667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784cd7b78d54'
down_revision = 'f2be59aa8a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('previous_analysis_id', sa.Integer(), nullable=True),
    sa.Column('comparison_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('improvement_score', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['skin_analysis.analysis_id'], ),
    sa.ForeignKeyConstraint(['previous_analysis_id'], ['skin_analysis.analysis_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison_history')
    # ### end Alembic commands ###
